<?php
/**
 * @file
 *
 * Hook implementations for twitter_post module.
 */

// Field API definitions.
require_once 'twitter_post.field.inc';

/**
 * Implements hook_permission().
 */
function twitter_post_permission() {
  return array(
    'post to twitter' => array(
      'title' => t('Post a message to Twitter'),
    ),
  );
}

/**
 * Implementation of hook_entity_insert().
 *
 * Intercepts newly created entities and posts notices to Twitter.
 */
function twitter_post_entity_insert($entity, $type) {
  // First we find twitter_post fields.
  list($id, $vid, $bundle) = entity_extract_ids($type, $entity);
  $fields_info = field_info_instances($type, $bundle);
  foreach ($fields_info as $field_name => $value) {
    $field_info = field_info_field($field_name);
    if ($field_info['type'] == 'twitter_post') {
      // Iterate field instances.
      foreach ($entity->{$field_name}[$entity->language] as $delta => $field_instance) {
        if (is_int($delta) && !empty($field_instance['account'])) {
          // Extract data out of each field.
          $status = $field_instance['status'];
          $message = $field_instance['message'];
          $twitter_account = entity_load_single('twitter_account', $field_instance['account']);
          // Post to Twitter if the status checkbox is active.
          if ($status) {
            module_load_include('inc', 'twitter');
            $message = token_replace($message, array($type => $entity));
            $status = twitter_set_status($twitter_account, $message);
            if ($status) {
              drupal_set_message(t('Successfully posted to Twitter: <a href="@status" target="_blank">@status</a>', array(
                '@status' => _twitter_status_url($status),
              )));
            }
          }
        }
      }
    }
  }
}

/**
 * Implementation of hook_entity_update().
 */
function twitter_post_entity_update($entity, $type) {
  twitter_post_entity_insert($entity, $type);
}
