<?php
/**
 * @file
 * Main module file for the openlayers_heatmaps module.
 */

/**
 * Implements hook_ctools_plugins_api().
 */
function openlayers_heatmaps_ctools_plugin_api($module, $api) {
  if ($module == "openlayers") {
    switch ($api) {
      case 'openlayers_layers':
      case 'openlayers_behaviors':
        return array('version' => 1);
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function openlayers_heatmaps_ctools_plugin_directory($module, $plugin) {
  if ($module == 'openlayers' && !empty($plugin)) {
    return 'openlayers_plugins/' . $plugin;
  }
}

function openlayers_heatmaps_libraries_info() {
  $libraries['heatmap.js'] = array(
    'name' => 'Heatmap.js',
    'vendor url' => 'http://openlayers.org/',
    'download url' => 'http://openlayers.org/download/OpenLayers-2.12.tar.gz',
    'version' => '2.x',
    'files' => array(
      'js' => array(
        'src/heatmap.js',
        'src/heatmap-openlayers.js'
      ),
    ),
  );

  return $libraries;
}
